# color scheme
[[plugins]]
repo  = 'sjl/badwolf'
hook_add = '''
    colorscheme badwolf
'''

# dein
[[plugins]]
repo = 'Shougo/dein.vim'

repo = 'itchyny/lightline.vim'
hook_add = '''
    let g:lightline = {'colorscheme': 'wombat'}
'''

# Toml
[[plugins]]
repo  = 'cespare/vim-toml'

# undoリスト
[[plugins]]
repo = 'mbbill/undotree'
hook_add = '''
if has("persistent_undo")
   " ファイルを閉じてもUndo記録を残す
    set undodir=~/.cache/.undodir/
    set undofile
endif
let g:undotree_WindowLayout = 2         " undotreeは左側/diffは下にウィンドウ幅で表示
let g:undotree_ShortIndicators = 1      " 時間単位は短く表示
let g:undotree_SplitWidth = 30          " undotreeのウィンドウ幅
let g:undotree_SetFocusWhenToggle = 1   " undotreeを開いたらフォーカスする
"let g:undotree_DiffAutoOpen = 0         " diffウィンドウは起動時無効
let g:undotree_DiffpanelHeight = 8      " diffウィンドウの行数
"let g:undotree_HighlightChangedText = 0 " 変更箇所のハイライト無効
" undotreeをトグル表示
noremap <Leader>u :UndotreeToggle<CR>

" undotreeバッファ内でのキーバインド設定
function! g:Undotree_CustomMap()
    map <silent> <buffer> <Esc> q
    map <silent> <buffer> h ?
endfunction
'''

# lint tool
[[plugins]]
repo = 'dense-analysis/ale'
hook_add = '''
let g:ale_linters = {
    \ 'python': ['flake8'],
    \ 'html': [],
    \ 'css': ['stylelint'],
    \ 'javascript': ['eslint'],
    \ 'vue': ['eslint', 'vls']
    \ }
let g:ale_fixers = {
    \'*': ['remove_trailing_lines', 'trim_whitespace'],
    \ 'python': ['black', 'isort'],
    \ 'javascript': ['eslint'],
    \ }

"行頭のマークが出る部分を常に表示するようにする
let g:ale_sign_column_always = 1

"ファイル保存時に整形実行
let g:ale_fix_on_save = 1

" エラー行にカーソルをあわせた際に表示されるメッセージフォーマット
let g:ale_echo_msg_format = '[%linter%]%code: %%s'
highlight link ALEErrorSign Tag
highlight link ALEWarningSign StorageClass

" Ctrl + jで次の指摘へ、Ctrl + kで前の指摘へ移動
nmap <silent> <C-J> <Plug>(ale_previous_wrap)
nmap <silent> <C-K> <Plug>(ale_next_wrap)
'''

# nerdtree
[[plugins]]
repo = 'preservim/nerdtree'

# nerdtreeをtab間で共有できるやつ
[[plugins]]
repo = 'jistr/vim-nerdtree-tabs'
hook_add = '''
nmap <C-n> :NERDTreeTabsToggle<CR>
let g:airline#extensions#tabline#enabled = 1
'''

# icon
[[plugins]]
repo = 'ryanoasis/vim-devicons'
